# fly.toml app configuration file generated for n74-custom-reports on 2023-06-05T15:49:58+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hxp-shopapp-n74-custom-reports"
primary_region = "ord"

[env]
  PORT = "8081"
  HOST = "https://hxp-shopapp-n74-custom-reports.fly.dev"
  SHOPIFY_API_KEY = "200d70e1f056306b936680f330b65039"
  SCOPES = "write_products"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
