# SHOPIFY_VOLUME_DISCOUNT_ORDER_ID=01H57MKXZBBYMM2ZQGTRA8Z1GP

name = "volume-discount-order"
type = "order_discounts"
api_version = "2023-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/shopify-functions/volume-discount-order/:functionId/new"
details = "/shopify-functions/volume-discount-order/:functionId/:id"